<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerECDY0ax\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerECDY0ax/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerECDY0ax.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerECDY0ax\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerECDY0ax\App_KernelProdContainer([
    'container.build_hash' => 'ECDY0ax',
    'container.build_id' => 'ba46c465',
    'container.build_time' => 1746603138,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerECDY0ax');
