<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerG7B2TkR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerG7B2TkR/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerG7B2TkR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerG7B2TkR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerG7B2TkR\App_KernelProdContainer([
    'container.build_hash' => 'G7B2TkR',
    'container.build_id' => '7f0f97c4',
    'container.build_time' => 1746609760,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerG7B2TkR');
