<?php

namespace ContainerFunS3ZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HKN_4cPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HKN.4cP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HKN.4cP'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'ChatMessage' => ['privates', '.errored..service_locator.HKN.4cP.App\\Entity\\ChatMessage', NULL, 'Cannot autowire service ".service_locator.HKN.4cP": it references class "App\\Entity\\ChatMessage" but no such service exists.'],
        ], [
            'ChatMessage' => 'App\\Entity\\ChatMessage',
        ]);
    }
}
