<?php

namespace ContainerFunS3ZI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatMessage2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.XBbge8f.App\Entity\ChatMessage' shared service.
     *
     * @return \App\Entity\ChatMessage
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.XBbge8f": it references class "App\\Entity\\ChatMessage" but no such service exists.');
    }
}
