<?php

namespace ContainerWlqbJdx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCar2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sXLt_rb.App\Entity\Car' shared service.
     *
     * @return \App\Entity\Car
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sXLt_rb": it references class "App\\Entity\\Car" but no such service exists.');
    }
}
