<?php

namespace ContainerYUxJ4Wy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UWQT4QuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uWQT4Qu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uWQT4Qu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chat' => ['privates', '.errored..service_locator.uWQT4Qu.App\\Entity\\Chat', NULL, 'Cannot autowire service ".service_locator.uWQT4Qu": it references class "App\\Entity\\Chat" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chat' => 'App\\Entity\\Chat',
            'entityManager' => '?',
        ]);
    }
}
