<?php

namespace ContainerH2S5x7G;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator..1epvCf.App\Entity\Review' shared service.
     *
     * @return \App\Entity\Review
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator..1epvCf": it references class "App\\Entity\\Review" but no such service exists.');
    }
}
