<?php

namespace ContainerWrznHzd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Xu0jtj3Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xu0jtj3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xu0jtj3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'transactionRepository' => ['privates', 'App\\Repository\\TransactionRepository', 'getTransactionRepositoryService', true],
            'userRepository' => ['services', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'carRepository' => 'App\\Repository\\CarRepository',
            'transactionRepository' => 'App\\Repository\\TransactionRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
