<?php

namespace ContainerWrznHzd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarFavoriteRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\CarFavoriteRepository' shared autowired service.
     *
     * @return \App\Repository\CarFavoriteRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\CarFavoriteRepository'] = new \App\Repository\CarFavoriteRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
