<?php

namespace ContainerVkfqJT7;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_Client_Authentication_WebsocketProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_web_socket.client.authentication.websocket_provider' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Client\Auth\WebsocketAuthenticationProvider
     *
     * @deprecated Since gos/web-socket-bundle 3.11: The "gos_web_socket.client.authentication.websocket_provider" service is deprecated and will be removed in GosWebSocketBundle 4.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('gos/web-socket-bundle', '3.11', 'The "gos_web_socket.client.authentication.websocket_provider" service is deprecated and will be removed in GosWebSocketBundle 4.0.');

        $container->privates['gos_web_socket.client.authentication.websocket_provider'] = $instance = new \Gos\Bundle\WebSocketBundle\Client\Auth\WebsocketAuthenticationProvider(($container->privates['gos_web_socket.client.storage'] ?? $container->load('getGosWebSocket_Client_StorageService')), $container->parameters['gos_web_socket.firewall']);

        $instance->setLogger(($container->privates['monolog.logger.websocket'] ?? $container->load('getMonolog_Logger_WebsocketService')));

        return $instance;
    }
}
