<?php

namespace ContainerCNq8t3i;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_EventListener_ClosePusherConnectionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_web_socket.event_listener.close_pusher_connections' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\EventListener\ClosePusherConnectionsListener
     *
     * @deprecated Since gos/web-socket-bundle 3.1: The "gos_web_socket.event_listener.close_pusher_connections" service is deprecated and will be removed in GosWebSocketBundle 4.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('gos/web-socket-bundle', '3.1', 'The "gos_web_socket.event_listener.close_pusher_connections" service is deprecated and will be removed in GosWebSocketBundle 4.0.');

        return $container->privates['gos_web_socket.event_listener.close_pusher_connections'] = new \Gos\Bundle\WebSocketBundle\EventListener\ClosePusherConnectionsListener(($container->services['gos_web_socket.registry.pusher'] ?? $container->load('getGosWebSocket_Registry_PusherService')));
    }
}
