<?php

namespace ContainerXLRHEpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_EventListener_StartServerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_web_socket.event_listener.start_server' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\EventListener\StartServerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/EventListener/StartServerListener.php';
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Registry/PeriodicRegistry.php';

        $container->privates['gos_web_socket.event_listener.start_server'] = $instance = new \Gos\Bundle\WebSocketBundle\EventListener\StartServerListener(($container->services['.container.private.gos_web_socket.registry.periodic'] ?? ($container->services['.container.private.gos_web_socket.registry.periodic'] = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\PeriodicRegistry())), ($container->services['gos_web_socket.registry.server_push_handler'] ?? $container->load('getGosWebSocket_Registry_ServerPushHandlerService')));

        $instance->setLogger(($container->privates['monolog.logger.websocket'] ?? $container->load('getMonolog_Logger_WebsocketService')));

        return $instance;
    }
}
