# config/packages/cache.yaml
framework:
    cache:
        default_redis_provider: 'redis://localhost:6379'
        pools:
            app.cache:
                adapter: cache.adapter.redis
                provider: '%env(REDIS_URL)%'
                default_lifetime: 3600
