framework:
    messenger:
        # Definimos los transportes, en este caso, usando Redis
        transports:
            async:
                dsn: 'redis://localhost:6379/messages'  # Redis transport
                options:
                    # Cambiamos a un valor numérico para el serializer
                    serializer: 1  # Este es el valor esperado de tipo int, que representa un serializer predeterminado

        # Enrutamos el mensaje LoadMessagesMessage al transport async
        routing:
            'App\Message\LoadMessagesMessage': async
