security:
    password_hashers:
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: id
    firewalls:
        # Configuración para la ruta de login (sin autenticación)
        login:
            pattern: ^/api/login$
            security: false  # Esta ruta no requiere autenticación
            
        refreshToken:
            pattern: ^/api/refreshToken$
            security: false  # Esta ruta no requiere autenticación
            
        ChatMessageSend:
            pattern: ^/ChatMessage/\d+/send  # El patrón para la ruta específica
            security: false  # Desactiva la seguridad para esta ruta

        UserChangePassword:
            pattern: ^/user/\d+/change-password  # El patrón para la ruta específica
            jwt: ~ 
            stateless: true
        
        userIndex:
            pattern: ^/user/index  # El patrón para la ruta específica
            jwt: ~
            stateless: true  # Desactiva el estado para esta ruta
        transactionsStatistics:
            pattern: ^/transactions/statistics  # El patrón para la ruta específica
            jwt: ~
            stateless: true  # Desactiva el estado para esta ruta
        ChatList:
            pattern: ^/chat/index  # El patrón para la ruta específica
            jwt: ~  
            stateless: true  

        csrf-token:
            pattern: ^/csrf-token  # Excluye esta ruta del firewall JWT
            security: false  # Desactiva la seguridad para esta ruta
            
        ChatCreate:
            pattern:  ^/chat/create
            jwt: ~
            stateless: true
      
        # Configuración para todas las rutas /api (excepto /api/login y /api/verify-token)

    # Define todas las reglas de acceso en una sola sección
    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Login accesible sin autenticación previa
        - { path: ^/api/refreshToken, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # Registro accesible sin autenticación
        - { path: ^/api/verify-token, roles: IS_AUTHENTICATED_ANONYMOUSLY }  # La ruta verify-token también sin autenticación
        - { path: ^/api, roles: ROLE_USER }  # El resto de rutas requiere autenticación
        - { path: ^/chat, roles: ROLE_USER }  # Las rutas /chat requieren autenticación JWT
        - { path: ^/message, roles: ROLE_USER }  # Las rutas /message también requieren autenticación JWT
        - { path: ^/user/.*/change-password, roles: ROLE_USER }
        - { path: ^/transactions/statistics, roles: ROLE_ADMIN }
        - { path: ^/user/index, roles: ROLE_ADMIN }
