<?php

namespace ContainerHQuf6O0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Messenger_HandlerDescriptor_1r7HQEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.messenger.handler_descriptor.1r7HQ_E' shared service.
     *
     * @return \Symfony\Component\Messenger\Handler\HandlerDescriptor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/HandlerDescriptor.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/messenger/Handler/MessageHandlerInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Message/MessageHandler.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['.messenger.handler_descriptor.1r7HQ_E'])) {
            return $container->privates['.messenger.handler_descriptor.1r7HQ_E'];
        }

        return $container->privates['.messenger.handler_descriptor.1r7HQ_E'] = new \Symfony\Component\Messenger\Handler\HandlerDescriptor(new \App\Message\MessageHandler(($container->privates['App\\Repository\\ChatMessageRepository'] ?? $container->load('getChatMessageRepositoryService')), $a, ($container->services['cache.app'] ?? $container->getCache_AppService()), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService())), []);
    }
}
