<?php

namespace ContainerX4SFwrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HSM_OtxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HSM.otx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HSM.otx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'uploadService' => ['privates', 'App\\Service\\UploadService', NULL, 'Cannot autowire service "App\\Service\\UploadService": argument "$uploadDirectory" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'entityManager' => '?',
            'uploadService' => 'App\\Service\\UploadService',
        ]);
    }
}
