<?php

namespace ContainerX4SFwrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WT7gsdDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wT7gsdD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wT7gsdD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chat' => ['privates', '.errored..service_locator.wT7gsdD.App\\Entity\\Chat', NULL, 'Cannot autowire service ".service_locator.wT7gsdD": it references class "App\\Entity\\Chat" but no such service exists.'],
        ], [
            'chat' => 'App\\Entity\\Chat',
        ]);
    }
}
