<?php

namespace ContainerX4SFwrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosPubsubRouter_Command_DebugRouterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_pubsub_router.command.debug_router' shared service.
     *
     * @return \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/gos/pubsub-router-bundle/src/Command/DebugRouterCommand.php';

        $container->privates['gos_pubsub_router.command.debug_router'] = $instance = new \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand(($container->services['.container.private.gos_pubsub_router.router_registry'] ?? $container->load('get_Container_Private_GosPubsubRouter_RouterRegistryService')));

        $instance->setName('gos:pubsub-router:debug');
        $instance->setDescription('Display current routes for a pubsub router');

        return $instance;
    }
}
