<?php

namespace ContainerX4SFwrh;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\UploadService' shared autowired service.
     *
     * @return \App\Service\UploadService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service "App\\Service\\UploadService": argument "$uploadDirectory" of method "__construct()" is type-hinted "string", you should configure its value explicitly.');
    }
}
