<?php

namespace Container8FZJJgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatMessageTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ChatMessageType' shared autowired service.
     *
     * @return \App\Form\ChatMessageType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ChatMessageType.php';

        return $container->privates['App\\Form\\ChatMessageType'] = new \App\Form\ChatMessageType();
    }
}
