<?php

namespace Container8FZJJgq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_EventListener_ClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_web_socket.event_listener.client' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\EventListener\ClientEventListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/EventListener/ClientEventListener.php';

        $container->privates['gos_web_socket.event_listener.client'] = $instance = new \Gos\Bundle\WebSocketBundle\EventListener\ClientEventListener(($container->privates['gos_web_socket.client.storage'] ?? $container->load('getGosWebSocket_Client_StorageService')), ($container->privates['gos_web_socket.client.authentication.websocket_provider'] ?? $container->load('getGosWebSocket_Client_Authentication_WebsocketProviderService')));

        $instance->setLogger(($container->privates['monolog.logger.websocket'] ?? $container->load('getMonolog_Logger_WebsocketService')));

        return $instance;
    }
}
