<?php

namespace ContainerSbmR9qq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosPubsubRouter_RouterRegistryService extends App_KernelProdContainer
{
    /*
     * Gets the public '.container.private.gos_pubsub_router.router_registry' shared service.
     *
     * @return \Gos\Bundle\PubSubRouterBundle\Router\RouterRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['.container.private.gos_pubsub_router.router_registry'] = $instance = new \Gos\Bundle\PubSubRouterBundle\Router\RouterRegistry();

        $instance->addRouter(($container->privates['gos_pubsub_router.router.websocket'] ?? $container->load('getGosPubsubRouter_Router_WebsocketService')));

        return $instance;
    }
}
