<?php

namespace ContainerSbmR9qq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Registry_OriginsService extends App_KernelProdContainer
{
    /*
     * Gets the public '.container.private.gos_web_socket.registry.origins' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Server\App\Registry\OriginRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['.container.private.gos_web_socket.registry.origins'] = $instance = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\OriginRegistry();

        $instance->addOrigin('http://localhost:3000');
        $instance->addOrigin('http://localhost');

        return $instance;
    }
}
