<?php

namespace ContainerSbmR9qq;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_Command_WebsocketServerService extends App_KernelProdContainer
{
    /*
     * Gets the private 'gos_web_socket.command.websocket_server' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Command\WebsocketServerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['gos_web_socket.command.websocket_server'] = $instance = new \Gos\Bundle\WebSocketBundle\Command\WebsocketServerCommand(($container->services['.container.private.gos_web_socket.server.launcher'] ?? $container->load('get_Container_Private_GosWebSocket_Server_LauncherService')), $container->getEnv('WEB_SOCKET_HOST'), $container->getEnv('WEB_SOCKET_PORT'), ($container->services['.container.private.gos_web_socket.registry.server'] ?? $container->load('get_Container_Private_GosWebSocket_Registry_ServerService')));

        $instance->setName('gos:websocket:server');
        $instance->setDescription('Starts the websocket server');

        return $instance;
    }
}
