<?php

namespace ContainerW7xVz5y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Authenticator_ChatListService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.authenticator.ChatList' shared service.
     *
     * @return \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.jwt.ChatList'] ?? $container->load('getSecurity_Authenticator_Jwt_ChatListService'));

        if (isset($container->privates['security.firewall.authenticator.ChatList'])) {
            return $container->privates['security.firewall.authenticator.ChatList'];
        }

        return $container->privates['security.firewall.authenticator.ChatList'] = new \Symfony\Component\Security\Http\Firewall\AuthenticatorManagerListener(new \Symfony\Component\Security\Http\Authentication\AuthenticatorManager([0 => $a], ($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.event_dispatcher.ChatList'] ?? $container->load('getSecurity_EventDispatcher_ChatListService')), 'ChatList', ($container->privates['monolog.logger.security'] ?? $container->load('getMonolog_Logger_SecurityService')), true, true, []));
    }
}
