<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6WlkwQW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6WlkwQW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6WlkwQW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6WlkwQW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6WlkwQW\App_KernelDevDebugContainer([
    'container.build_hash' => '6WlkwQW',
    'container.build_id' => 'd4e1431c',
    'container.build_time' => 1741697205,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6WlkwQW');
