<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUeFItiS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUeFItiS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUeFItiS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUeFItiS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUeFItiS\App_KernelDevDebugContainer([
    'container.build_hash' => 'UeFItiS',
    'container.build_id' => '26a3ea73',
    'container.build_time' => 1741249710,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUeFItiS');
