<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOC8xX9E\App_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOC8xX9E/App_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerOC8xX9E.legacy');

    return;
}

if (!\class_exists(App_KernelDevContainer::class, false)) {
    \class_alias(\ContainerOC8xX9E\App_KernelDevContainer::class, App_KernelDevContainer::class, false);
}

return new \ContainerOC8xX9E\App_KernelDevContainer([
    'container.build_hash' => 'OC8xX9E',
    'container.build_id' => '761f997e',
    'container.build_time' => 1747128879,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOC8xX9E');
