<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5xkXOdi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5xkXOdi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container5xkXOdi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container5xkXOdi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container5xkXOdi\App_KernelDevDebugContainer([
    'container.build_hash' => '5xkXOdi',
    'container.build_id' => '9fc58cf6',
    'container.build_time' => 1743498080,
], __DIR__.\DIRECTORY_SEPARATOR.'Container5xkXOdi');
