<?php

namespace ContainerQn0E2Up;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Dispatcher_RpcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.dispatcher.rpc' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\RpcDispatcher
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Dispatcher/RpcDispatcherInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Dispatcher/RpcDispatcher.php';
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Registry/RpcRegistry.php';

        $container->services['.container.private.gos_web_socket.dispatcher.rpc'] = $instance = new \Gos\Bundle\WebSocketBundle\Server\App\Dispatcher\RpcDispatcher(($container->services['.container.private.gos_web_socket.registry.rpc'] ?? ($container->services['.container.private.gos_web_socket.registry.rpc'] = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\RpcRegistry())));

        $instance->setLogger(($container->privates['monolog.logger.websocket'] ?? $container->load('getMonolog_Logger_WebsocketService')));

        return $instance;
    }
}
