<?php

namespace ContainerG7B2TkR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6JWkYvService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6JWk_Yv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6JWk_Yv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carFavorite' => ['privates', '.errored..service_locator.6JWk_Yv.App\\Entity\\CarFavorite', NULL, 'Cannot autowire service ".service_locator.6JWk_Yv": it references class "App\\Entity\\CarFavorite" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'carFavorite' => 'App\\Entity\\CarFavorite',
            'entityManager' => '?',
        ]);
    }
}
