<?php

namespace ContainerG7B2TkR;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\CarType' shared autowired service.
     *
     * @return \App\Form\CarType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\CarType'] = new \App\Form\CarType();
    }
}
