<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDjI0Wfz\App_KernelCLOUDINARY_CLOUD_NAMEContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDjI0Wfz/App_KernelCLOUDINARY_CLOUD_NAMEContainer.php') {
    touch(__DIR__.'/ContainerDjI0Wfz.legacy');

    return;
}

if (!\class_exists(App_KernelCLOUDINARY_CLOUD_NAMEContainer::class, false)) {
    \class_alias(\ContainerDjI0Wfz\App_KernelCLOUDINARY_CLOUD_NAMEContainer::class, App_KernelCLOUDINARY_CLOUD_NAMEContainer::class, false);
}

return new \ContainerDjI0Wfz\App_KernelCLOUDINARY_CLOUD_NAMEContainer([
    'container.build_hash' => 'DjI0Wfz',
    'container.build_id' => 'fd73df93',
    'container.build_time' => 1746604784,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDjI0Wfz');
