<?php

namespace ContainerJL2oplx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SXLtRbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sXLt_rb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sXLt_rb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'car' => ['privates', '.errored..service_locator.sXLt_rb.App\\Entity\\Car', NULL, 'Cannot autowire service ".service_locator.sXLt_rb": it references class "App\\Entity\\Car" but no such service exists.'],
        ], [
            'car' => 'App\\Entity\\Car',
        ]);
    }
}
