<?php

namespace ContainerJL2oplx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Client_ManipulatorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.client.manipulator' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Client\ClientManipulator
     *
     * @deprecated Since gos/web-socket-bundle 3.11: The ".container.private.gos_web_socket.client.manipulator" service is deprecated and will be removed in GosWebSocketBundle 4.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('gos/web-socket-bundle', '3.11', 'The ".container.private.gos_web_socket.client.manipulator" service is deprecated and will be removed in GosWebSocketBundle 4.0.');

        return $container->services['.container.private.gos_web_socket.client.manipulator'] = new \Gos\Bundle\WebSocketBundle\Client\ClientManipulator(($container->privates['gos_web_socket.client.storage'] ?? $container->load('getGosWebSocket_Client_StorageService')), ($container->privates['gos_web_socket.client.authentication.websocket_provider'] ?? $container->load('getGosWebSocket_Client_Authentication_WebsocketProviderService')));
    }
}
