<?php

namespace Container3tf4Uz5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\CarController' shared autowired service.
     *
     * @return \App\Controller\CarController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\CarController'] = $instance = new \App\Controller\CarController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\CarController', $container));

        return $instance;
    }
}
