<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Chat extends \App\Entity\Chat implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'buyer' => [parent::class, 'buyer', null],
        "\0".parent::class."\0".'car' => [parent::class, 'car', null],
        "\0".parent::class."\0".'createdDate' => [parent::class, 'createdDate', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'seller' => [parent::class, 'seller', null],
        'buyer' => [parent::class, 'buyer', null],
        'car' => [parent::class, 'car', null],
        'createdDate' => [parent::class, 'createdDate', null],
        'id' => [parent::class, 'id', null],
        'seller' => [parent::class, 'seller', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
