<?php

namespace Container7cSOXak;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\ChatType' shared autowired service.
     *
     * @return \App\Form\ChatType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Form\\ChatType'] = new \App\Form\ChatType();
    }
}
