<?php

namespace ContainerDjI0Wfz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OZJDMQiService extends App_KernelCLOUDINARY_CLOUD_NAMEContainer
{
    /*
     * Gets the private '.service_locator.oZJDMQi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oZJDMQi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'cloudinaryService' => ['privates', 'App\\Service\\CloudinaryService', NULL, 'You have requested a non-existent parameter "cloudinary.cloud_name". You cannot access nested array items, do you want to inject "cloudinary" instead?'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'cloudinaryService' => 'App\\Service\\CloudinaryService',
            'entityManager' => '?',
        ]);
    }
}
