<?php

namespace ContainerDjI0Wfz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UTa2lwWService extends App_KernelCLOUDINARY_CLOUD_NAMEContainer
{
    /*
     * Gets the private '.service_locator.UTa2lwW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.UTa2lwW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carRepository' => ['privates', 'App\\Repository\\CarRepository', 'getCarRepositoryService', true],
            'logger' => ['privates', 'monolog.logger', 'getMonolog_LoggerService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
        ], [
            'carRepository' => 'App\\Repository\\CarRepository',
            'logger' => '?',
            'serializer' => '?',
        ]);
    }
}
