<?php

namespace ContainerDjI0Wfz;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatMessageRepositoryService extends App_KernelCLOUDINARY_CLOUD_NAMEContainer
{
    /*
     * Gets the private 'App\Repository\ChatMessageRepository' shared autowired service.
     *
     * @return \App\Repository\ChatMessageRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\ChatMessageRepository'] = new \App\Repository\ChatMessageRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
