<?php

namespace ContainerXLRHEpT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJwtUserProviderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\JwtUserProvider' shared autowired service.
     *
     * @return \App\Security\JwtUserProvider
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/security-core/User/UserProviderInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Security/JwtUserProvider.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService());

        if (isset($container->privates['App\\Security\\JwtUserProvider'])) {
            return $container->privates['App\\Security\\JwtUserProvider'];
        }

        return $container->privates['App\\Security\\JwtUserProvider'] = new \App\Security\JwtUserProvider($a);
    }
}
