<?php

namespace Container0Ued4Wv;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_ChatCreateService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.map.context.ChatCreate' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['security.authenticator.jwt.ChatCreate'] ?? $container->load('getSecurity_Authenticator_Jwt_ChatCreateService'));

        if (isset($container->privates['security.firewall.map.context.ChatCreate'])) {
            return $container->privates['security.firewall.map.context.ChatCreate'];
        }

        return $container->privates['security.firewall.map.context.ChatCreate'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['security.channel_listener'] ?? $container->load('getSecurity_ChannelListenerService'));
            yield 1 => ($container->privates['security.context_listener.3'] ?? $container->getSecurity_ContextListener_3Service());
            yield 2 => ($container->privates['security.firewall.authenticator.ChatCreate'] ?? $container->load('getSecurity_Firewall_Authenticator_ChatCreateService'));
            yield 3 => ($container->privates['security.access_listener'] ?? $container->load('getSecurity_AccessListenerService'));
        }, 4), new \Symfony\Component\Security\Http\Firewall\ExceptionListener(($container->privates['security.token_storage'] ?? $container->getSecurity_TokenStorageService()), ($container->privates['security.authentication.trust_resolver'] ?? ($container->privates['security.authentication.trust_resolver'] = new \Symfony\Component\Security\Core\Authentication\AuthenticationTrustResolver())), ($container->privates['security.http_utils'] ?? $container->load('getSecurity_HttpUtilsService')), 'ChatCreate', $a, NULL, NULL, ($container->privates['monolog.logger.security'] ?? $container->getMonolog_Logger_SecurityService()), false), NULL, new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('ChatCreate', 'security.user_checker', '.security.request_matcher.O05mk5k', true, false, 'security.user.provider.concrete.app_user_provider', 'ChatCreate', 'security.authenticator.jwt.ChatCreate', NULL, NULL, [0 => 'jwt'], NULL));
    }
}
