<?php

namespace Container3mChoBr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uWQT4Qu.App\Entity\Chat' shared service.
     *
     * @return \App\Entity\Chat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uWQT4Qu": it references class "App\\Entity\\Chat" but no such service exists.');
    }
}
