<?php

namespace ContainerDNYziBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VQ105EGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vQ105EG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vQ105EG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatRepository' => ['privates', 'App\\Repository\\ChatRepository', 'getChatRepositoryService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'chatRepository' => 'App\\Repository\\ChatRepository',
            'entityManager' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
