<?php

namespace ContainerDNYziBW;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K1zp18YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.k1zp18Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.k1zp18Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.ChatCreate' => ['privates', 'security.event_dispatcher.ChatCreate', 'getSecurity_EventDispatcher_ChatCreateService', false],
            'security.event_dispatcher.UserChangePassword' => ['privates', 'security.event_dispatcher.UserChangePassword', 'getSecurity_EventDispatcher_UserChangePasswordService', false],
            'security.event_dispatcher.api' => ['privates', 'security.event_dispatcher.api', 'getSecurity_EventDispatcher_ApiService', true],
        ], [
            'event_dispatcher' => '?',
            'security.event_dispatcher.ChatCreate' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.UserChangePassword' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.api' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
        ]);
    }
}
