<?php

namespace ContainerUeFItiS;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChat2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.wT7gsdD.App\Entity\Chat' shared service.
     *
     * @return \App\Entity\Chat
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.wT7gsdD": it references class "App\\Entity\\Chat" but no such service exists.');
    }
}
