<?php

namespace ContainerOC8xX9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhC_VRSService extends App_KernelDevContainer
{
    /*
     * Gets the private '.service_locator.jhC.VRS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jhC.VRS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'event_dispatcher' => ['services', 'event_dispatcher', 'getEventDispatcherService', false],
            'security.event_dispatcher.ChatCreate' => ['privates', 'security.event_dispatcher.ChatCreate', 'getSecurity_EventDispatcher_ChatCreateService', true],
            'security.event_dispatcher.ChatList' => ['privates', 'security.event_dispatcher.ChatList', 'getSecurity_EventDispatcher_ChatListService', true],
            'security.event_dispatcher.UserChangePassword' => ['privates', 'security.event_dispatcher.UserChangePassword', 'getSecurity_EventDispatcher_UserChangePasswordService', true],
            'security.event_dispatcher.userIndex' => ['privates', 'security.event_dispatcher.userIndex', 'getSecurity_EventDispatcher_UserIndexService', true],
        ], [
            'event_dispatcher' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.ChatCreate' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.ChatList' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.UserChangePassword' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
            'security.event_dispatcher.userIndex' => 'Symfony\\Component\\EventDispatcher\\EventDispatcher',
        ]);
    }
}
