<?php

namespace ContainerOC8xX9E;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Maker_AutoCommand_MakeDataPersister_LazyService extends App_KernelDevContainer
{
    /*
     * Gets the private '.maker.auto_command.make_data_persister.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.maker.auto_command.make_data_persister.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('make:data-persister', [], 'Creates an API Platform data persister', false, function () use ($container): \Symfony\Bundle\MakerBundle\Command\MakerCommand {
            return ($container->privates['maker.auto_command.make_data_persister'] ?? $container->load('getMaker_AutoCommand_MakeDataPersisterService'));
        });
    }
}
