<?php

namespace Container0B7sxjM;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BA3xqGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BA3xq_G' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BA3xq_G'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'car' => ['privates', '.errored..service_locator.BA3xq_G.App\\Entity\\Car', NULL, 'Cannot autowire service ".service_locator.BA3xq_G": it references class "App\\Entity\\Car" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'car' => 'App\\Entity\\Car',
            'entityManager' => '?',
        ]);
    }
}
