<?php

namespace ContainerZaBQtjj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Registry_TopicService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.registry.topic' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Server\App\Registry\TopicRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Registry/TopicRegistry.php';

        return $container->services['.container.private.gos_web_socket.registry.topic'] = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\TopicRegistry();
    }
}
