<?php

namespace ContainerZaBQtjj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_GosPubsubRouter_Command_DebugRouter_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.gos_pubsub_router.command.debug_router.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.gos_pubsub_router.command.debug_router.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('gos:pubsub-router:debug', [], 'Display current routes for a pubsub router', false, function () use ($container): \Gos\Bundle\PubSubRouterBundle\Command\DebugRouterCommand {
            return ($container->privates['gos_pubsub_router.command.debug_router'] ?? $container->load('getGosPubsubRouter_Command_DebugRouterService'));
        });
    }
}
