<?php

namespace ContainerMIcroeY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatCarControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\ChatCarController' shared autowired service.
     *
     * @return \App\Controller\ChatCarController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/ChatCarController.php';

        $container->services['App\\Controller\\ChatCarController'] = $instance = new \App\Controller\ChatCarController();

        $instance->setContainer(($container->privates['.service_locator.jIxfAsi'] ?? $container->load('get_ServiceLocator_JIxfAsiService'))->withContext('App\\Controller\\ChatCarController', $container));

        return $instance;
    }
}
