<?php

namespace ContainerUJT4R4U;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MWTaHqKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.mWTaHqK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.mWTaHqK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessage' => ['privates', '.errored..service_locator.mWTaHqK.App\\Entity\\ChatMessage', NULL, 'Cannot autowire service ".service_locator.mWTaHqK": it references class "App\\Entity\\ChatMessage" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'chatMessage' => 'App\\Entity\\ChatMessage',
            'entityManager' => '?',
        ]);
    }
}
