<?php

namespace ContainerOwryYcV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Firewall_Map_Context_RefreshTokenService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.firewall.map.context.refreshToken' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Security\FirewallContext
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['security.firewall.map.context.refreshToken'] = new \Symfony\Bundle\SecurityBundle\Security\FirewallContext(new RewindableGenerator(function () use ($container) {
            return new \EmptyIterator();
        }, 0), NULL, NULL, new \Symfony\Bundle\SecurityBundle\Security\FirewallConfig('refreshToken', 'security.user_checker', '.security.request_matcher.zUz4DiV', false, false, NULL, NULL, NULL, NULL, NULL, [], NULL));
    }
}
