<?php

namespace ContainerECDY0ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCloudinaryServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\CloudinaryService' shared autowired service.
     *
     * @return \App\Service\CloudinaryService
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('You have requested a non-existent parameter "cloudinary.cloud_name". You cannot access nested array items, do you want to inject "cloudinary" instead?');
    }
}
