<?php

namespace ContainerECDY0ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCarFavorite2Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.6JWk_Yv.App\Entity\CarFavorite' shared service.
     *
     * @return \App\Entity\CarFavorite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6JWk_Yv": it references class "App\\Entity\\CarFavorite" but no such service exists.');
    }
}
