<?php

namespace ContainerECDY0ax;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurity_Command_DebugFirewallService extends App_KernelProdContainer
{
    /*
     * Gets the private 'security.command.debug_firewall' shared service.
     *
     * @return \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['security.command.debug_firewall'] = $instance = new \Symfony\Bundle\SecurityBundle\Command\DebugFirewallCommand($container->parameters['security.firewalls'], ($container->privates['.service_locator.gcVH11s'] ?? $container->get_ServiceLocator_GcVH11sService()), ($container->privates['.service_locator.jhC.VRS'] ?? $container->load('get_ServiceLocator_JhC_VRSService')), ['UserChangePassword' => [0 => ($container->privates['security.authenticator.jwt.UserChangePassword'] ?? $container->load('getSecurity_Authenticator_Jwt_UserChangePasswordService'))], 'userIndex' => [0 => ($container->privates['security.authenticator.jwt.userIndex'] ?? $container->load('getSecurity_Authenticator_Jwt_UserIndexService'))], 'ChatList' => [0 => ($container->privates['security.authenticator.jwt.ChatList'] ?? $container->load('getSecurity_Authenticator_Jwt_ChatListService'))], 'ChatCreate' => [0 => ($container->privates['security.authenticator.jwt.ChatCreate'] ?? $container->load('getSecurity_Authenticator_Jwt_ChatCreateService'))]], false);

        $instance->setName('debug:firewall');
        $instance->setDescription('Display information about your security firewall(s)');

        return $instance;
    }
}
