<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transaction extends \App\Entity\Transaction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'buyer' => [parent::class, 'buyer', null, 16],
        "\0".parent::class."\0".'car' => [parent::class, 'car', null, 16],
        "\0".parent::class."\0".'commission' => [parent::class, 'commission', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isIncomeReported' => [parent::class, 'isIncomeReported', null, 16],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null, 16],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null, 16],
        "\0".parent::class."\0".'totalIncome' => [parent::class, 'totalIncome', null, 16],
        "\0".parent::class."\0".'transactionDate' => [parent::class, 'transactionDate', null, 16],
        'buyer' => [parent::class, 'buyer', null, 16],
        'car' => [parent::class, 'car', null, 16],
        'commission' => [parent::class, 'commission', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isIncomeReported' => [parent::class, 'isIncomeReported', null, 16],
        'price' => [parent::class, 'price', null, 16],
        'status' => [parent::class, 'status', null, 16],
        'totalIncome' => [parent::class, 'totalIncome', null, 16],
        'transactionDate' => [parent::class, 'transactionDate', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
