<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ChatMessage extends \App\Entity\ChatMessage implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'chat' => [parent::class, 'chat', null, 16],
        "\0".parent::class."\0".'content' => [parent::class, 'content', null, 16],
        "\0".parent::class."\0".'idMessage' => [parent::class, 'idMessage', null, 16],
        "\0".parent::class."\0".'messageDate' => [parent::class, 'messageDate', null, 16],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null, 16],
        'chat' => [parent::class, 'chat', null, 16],
        'content' => [parent::class, 'content', null, 16],
        'idMessage' => [parent::class, 'idMessage', null, 16],
        'messageDate' => [parent::class, 'messageDate', null, 16],
        'user' => [parent::class, 'user', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
