<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Car extends \App\Entity\Car implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'CarCondition' => [parent::class, 'CarCondition', null],
        "\0".parent::class."\0".'CarSold' => [parent::class, 'CarSold', null],
        "\0".parent::class."\0".'brand' => [parent::class, 'brand', null],
        "\0".parent::class."\0".'city' => [parent::class, 'city', null],
        "\0".parent::class."\0".'color' => [parent::class, 'color', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'doors' => [parent::class, 'doors', null],
        "\0".parent::class."\0".'fuelType' => [parent::class, 'fuelType', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'images' => [parent::class, 'images', null],
        "\0".parent::class."\0".'lat' => [parent::class, 'lat', null],
        "\0".parent::class."\0".'lon' => [parent::class, 'lon', null],
        "\0".parent::class."\0".'manufacture_year' => [parent::class, 'manufacture_year', null],
        "\0".parent::class."\0".'mileage' => [parent::class, 'mileage', null],
        "\0".parent::class."\0".'model' => [parent::class, 'model', null],
        "\0".parent::class."\0".'price' => [parent::class, 'price', null],
        "\0".parent::class."\0".'publication_date' => [parent::class, 'publication_date', null],
        "\0".parent::class."\0".'seats' => [parent::class, 'seats', null],
        "\0".parent::class."\0".'traction' => [parent::class, 'traction', null],
        "\0".parent::class."\0".'transmission' => [parent::class, 'transmission', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'CarCondition' => [parent::class, 'CarCondition', null],
        'CarSold' => [parent::class, 'CarSold', null],
        'brand' => [parent::class, 'brand', null],
        'city' => [parent::class, 'city', null],
        'color' => [parent::class, 'color', null],
        'description' => [parent::class, 'description', null],
        'doors' => [parent::class, 'doors', null],
        'fuelType' => [parent::class, 'fuelType', null],
        'id' => [parent::class, 'id', null],
        'images' => [parent::class, 'images', null],
        'lat' => [parent::class, 'lat', null],
        'lon' => [parent::class, 'lon', null],
        'manufacture_year' => [parent::class, 'manufacture_year', null],
        'mileage' => [parent::class, 'mileage', null],
        'model' => [parent::class, 'model', null],
        'price' => [parent::class, 'price', null],
        'publication_date' => [parent::class, 'publication_date', null],
        'seats' => [parent::class, 'seats', null],
        'traction' => [parent::class, 'traction', null],
        'transmission' => [parent::class, 'transmission', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
