<?php

namespace ContainerFLZvvWa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_Registry_ServerPushHandlerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'gos_web_socket.registry.server_push_handler' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Pusher\ServerPushHandlerRegistry
     *
     * @deprecated Since gos/web-socket-bundle 3.1: The "gos_web_socket.registry.server_push_handler" service is deprecated and will be removed in GosWebSocketBundle 4.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('gos/web-socket-bundle', '3.1', 'The "gos_web_socket.registry.server_push_handler" service is deprecated and will be removed in GosWebSocketBundle 4.0.');

        return $container->services['gos_web_socket.registry.server_push_handler'] = new \Gos\Bundle\WebSocketBundle\Pusher\ServerPushHandlerRegistry();
    }
}
