<?php

namespace ContainerJgkoVEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hzlwdj0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hzlwdj0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hzlwdj0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carRepository' => ['privates', '.errored.V3l2vu6', NULL, 'Cannot determine controller argument for "App\\Controller\\ChatController::getUserChats()": the $carRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CarRepository". Did you forget to add a use statement?'],
            'chatRepository' => ['privates', 'App\\Repository\\ChatRepository', 'getChatRepositoryService', true],
        ], [
            'carRepository' => '?',
            'chatRepository' => 'App\\Repository\\ChatRepository',
        ]);
    }
}
