<?php

namespace ContainerJgkoVEx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_V3l2vu6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.V3l2vu6' shared service.
     *
     * @return \App\Controller\CarRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ChatController::getUserChats()": the $carRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\CarRepository". Did you forget to add a use statement?');
    }
}
