<?php

namespace ContainerXhwxGJq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PMI0SbeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PMI0Sbe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PMI0Sbe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessageRepository' => ['privates', 'App\\Repository\\ChatMessageRepository', 'getChatMessageRepositoryService', true],
        ], [
            'chatMessageRepository' => 'App\\Repository\\ChatMessageRepository',
        ]);
    }
}
