<?php

namespace Container0QKlxLQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TuQ5fRxService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TuQ5fRx' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TuQ5fRx'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'carFavoriteRepository' => ['privates', 'App\\Repository\\CarFavoriteRepository', 'getCarFavoriteRepositoryService', true],
        ], [
            'carFavoriteRepository' => 'App\\Repository\\CarFavoriteRepository',
        ]);
    }
}
