export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as SubmitCar } from './SubmitCar';
export { default as CarDetails } from './CarDetails';
export { default as Chat } from './Chat';
export { default as BuyCar } from './BuyCar';
export { default as Chats } from './Chats';
export { default as ErrorPage} from './ErrorPage';
export { default as CarFavorites} from './CarFavorites';
export { default as Profile} from './Profile';
export { default as SeeCars} from './SeeCars';
export { default as About} from './About';
export { default as Users} from './Users';
export { default as Chat_list} from './Chat_list';
export { default as Banned} from './Banned';
