<?php

namespace ContainerHUgz9Sn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3tQ0UtyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3tQ0Uty' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3tQ0Uty'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'chatMessage' => ['privates', '.errored..service_locator.3tQ0Uty.App\\Entity\\ChatMessage', NULL, 'Cannot autowire service ".service_locator.3tQ0Uty": it references class "App\\Entity\\ChatMessage" but no such service exists.'],
        ], [
            'chatMessage' => 'App\\Entity\\ChatMessage',
        ]);
    }
}
