<?php

namespace ContainerHUgz9Sn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Container_Private_GosWebSocket_Registry_OriginsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.container.private.gos_web_socket.registry.origins' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Server\App\Registry\OriginRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/gos/web-socket-bundle/src/Server/App/Registry/OriginRegistry.php';

        $container->services['.container.private.gos_web_socket.registry.origins'] = $instance = new \Gos\Bundle\WebSocketBundle\Server\App\Registry\OriginRegistry();

        $instance->addOrigin('192.168.1.132');

        return $instance;
    }
}
