<?php

namespace ContainerZ59XMUo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGosWebSocket_Client_Driver_InMemoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'gos_web_socket.client.driver.in_memory' shared service.
     *
     * @return \Gos\Bundle\WebSocketBundle\Client\Driver\InMemoryDriver
     *
     * @deprecated Since gos/web-socket-bundle 3.11: The "gos_web_socket.client.driver.in_memory" service is deprecated and will be removed in GosWebSocketBundle 4.0.
     */
    public static function do($container, $lazyLoad = true)
    {
        trigger_deprecation('gos/web-socket-bundle', '3.11', 'The "gos_web_socket.client.driver.in_memory" service is deprecated and will be removed in GosWebSocketBundle 4.0.');

        return new \Gos\Bundle\WebSocketBundle\Client\Driver\InMemoryDriver();
    }
}
